import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { reportService } from '../services/api';

function ReportPage() {
  const navigate = useNavigate();
  const [loading, setLoading] = useState(false);
  const [shareLoading, setShareLoading] = useState(false);
  const [message, setMessage] = useState({ type: '', text: '' });
  const [previewStats, setPreviewStats] = useState({
    tasksCompletedToday: '--',
    pendingTasks: '--',
    upcomingDeadlines: '--',
    weeklyProgress: '--%'
  });

  // Auto-refresh preview on mount
  useEffect(() => {
    refreshPreview();
  }, []);

  const refreshPreview = async () => {
    try {
      const response = await fetch('/api/user/stats', { 
        credentials: 'include',
        headers: { 'Accept': 'application/json' }
      });
      if (response.ok) {
        const data = await response.json();
        if (data.success) {
          setPreviewStats({
            tasksCompletedToday: data.data.tasksCompletedToday || 0,
            pendingTasks: data.data.pendingTasks || 0,
            upcomingDeadlines: data.data.upcomingDeadlines || 0,
            weeklyProgress: (data.data.weeklyProgress || 0) + '%'
          });
        }
      }
    } catch (error) {
      console.warn('Preview stats unavailable:', error);
    }
  };

  const makeDownload = (blob, filename) => {
    try {
      const url = window.URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = filename;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      window.URL.revokeObjectURL(url);
      return true;
    } catch (error) {
      console.error('Download failed:', error);
      throw new Error('Download trigger failed');
    }
  };

  const handleDownload = async () => {
    setLoading(true);
    setMessage({ type: '', text: '' });
    try {
      console.log('Starting report download...');
      const { blob, filename } = await reportService.getReportBlob();
      if (!blob || blob.size === 0) {
        throw new Error('Empty report generated');
      }
      const success = makeDownload(blob, filename);
      if (success) {
        setMessage({ 
          type: 'success', 
          text: `✅ Report "${filename}" downloaded to your Downloads folder!` 
        });
      }
    } catch (error) {
      console.error('Download error:', error);
      const errMsg = error.message || 'Failed to generate/download report. Check console/server.';
      setMessage({ type: 'error', text: errMsg });
    } finally {
      setLoading(false);
    }
  };

  const handleWhatsAppShare = async () => {
    setShareLoading(true);
    setMessage({ type: '', text: '' });

    try {
      console.log('Starting WhatsApp share flow...');
      // Step 1: Always download first
      const { blob, filename } = await reportService.getReportBlob();
      if (!blob || blob.size === 0) {
        throw new Error('Empty report generated');
      }
      makeDownload(blob, filename);

      // Step 2: Prepare share
      const generatedDate = new Date().toLocaleDateString('en-US', {
        weekday: 'long',
        year: 'numeric',
        month: 'long',
        day: 'numeric'
      });
      const shareText = `📊 *Smart Student Tasks Progress Report*

Hi! 

✅ I've downloaded my detailed progress report: *${filename}*

*Generated:* ${generatedDate}

📥 **The PDF is now in your Downloads folder. To share:**

1. Open the downloaded PDF from Downloads
2. In WhatsApp, attach the file from Gallery/Downloads/Documents
3. Send!

---
*Generated by Smart Student Tasks app*
`;

      // Step 3: Native share if mobile (files support)
      const isMobile = /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent);
      if (isMobile && navigator.canShare && navigator.canShare({ files: [new File([blob], filename, { type: 'application/pdf' })] })) {
        await navigator.share({
          files: [new File([blob], filename, { type: 'application/pdf' })],
          title: 'Progress Report',
          text: shareText.split('📥')[0], // Short text
        });
        setMessage({ 
          type: 'success', 
          text: `✅ Report shared natively! File attached automatically.` 
        });
      } else {
        // Desktop/fallback: WhatsApp web
        const whatsappUrl = `https://wa.me/?text=${encodeURIComponent(shareText)}`;
        window.open(whatsappUrl, '_blank', 'noopener,noreferrer');
        setMessage({ 
          type: 'success', 
          text: `✅ PDF downloaded! WhatsApp opened 👆. Attach "${filename}" from Downloads in chat.` 
        });
      }
    } catch (error) {
      console.error('WhatsApp share error:', error);
      setMessage({
        type: 'error',
        text: error.message || 'Share failed. Try download button first.'
      });
    } finally {
      setShareLoading(false);
    }
  };

  return (
    <div className="max-w-4xl mx-auto p-4 sm:p-6">
      <div className="mb-6">
        <button
          onClick={() => navigate('/dashboard')}
          className="flex items-center space-x-2 text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-white transition-colors"
        >
          <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
          </svg>
          <span>Back to Dashboard</span>
        </button>
      </div>

      <h1 className="text-3xl font-bold text-gray-900 dark:text-white mb-2">📊 Progress Report</h1>
      <p className="text-gray-500 dark:text-gray-400 mb-8">Generate PDF reports and share on WhatsApp</p>

      {message.text && (
        <div className={`p-4 rounded-lg mb-6 border-l-4 ${
          message.type === 'success' 
            ? 'bg-green-50 dark:bg-green-950/30 text-green-800 dark:text-green-200 border-green-400' 
            : 'bg-red-50 dark:bg-red-950/30 text-red-800 dark:text-red-200 border-red-400'
        }`}>
          <div className="flex">
            <div className="flex-shrink-0">
              {message.type === 'success' ? '✅' : '❌'}
            </div>
            <div className="ml-3">
              <p className="text-sm">{message.text}</p>
            </div>
          </div>
        </div>
      )}

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-8">
        {/* Download Card */}
        <div className="bg-white dark:bg-slate-800 rounded-2xl shadow-lg p-6 border border-gray-100 dark:border-slate-700 hover:shadow-xl transition-all">
          <div className="text-center">
            <div className="w-16 h-16 mx-auto mb-4 bg-blue-100 dark:bg-blue-900/20 rounded-2xl flex items-center justify-center">
              <svg className="w-8 h-8 text-blue-600 dark:text-blue-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
              </svg>
            </div>
            <h3 className="text-xl font-semibold text-gray-900 dark:text-white mb-2">📥 Download PDF</h3>
            <p className="text-gray-500 dark:text-gray-400 mb-6 text-sm">
              Get detailed report with charts & stats
            </p>
            <button
              onClick={handleDownload}
              disabled={loading}
              className="w-full px-6 py-3 bg-blue-600 hover:bg-blue-700 disabled:bg-blue-400 text-white rounded-xl font-semibold transition-all flex items-center justify-center space-x-2"
            >
              {loading ? (
                <>
                  <svg className="animate-spin -ml-1 h-5 w-5" fill="none" viewBox="0 0 24 24">
                    <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
                  </svg>
                  <span>Generating...</span>
                </>
              ) : (
                <>
                  <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
                  </svg>
                  <span>Download Report</span>
                </>
              )}
            </button>
          </div>
        </div>

        {/* WhatsApp Card */}
        <div className="bg-white dark:bg-slate-800 rounded-2xl shadow-lg p-6 border border-gray-100 dark:border-slate-700 hover:shadow-xl transition-all">
          <div className="text-center">
            <div className="w-16 h-16 mx-auto mb-4 bg-green-100 dark:bg-green-900/20 rounded-2xl flex items-center justify-center">
              <svg className="w-8 h-8 text-green-600 dark:text-green-400" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2} strokeLinecap="round" strokeLinejoin="round">
                <path d="M12 5v14m-5-5l5 5 5-5" />
              </svg>
            </div>
            <h3 className="text-xl font-semibold text-gray-900 dark:text-white mb-2">💬 Share on WhatsApp</h3>
            <p className="text-gray-500 dark:text-gray-400 mb-6 text-sm">
              Downloads PDF first, then opens WhatsApp chat
            </p>
            <button
              onClick={handleWhatsAppShare}
              disabled={shareLoading}
              className="w-full px-6 py-3 bg-green-600 hover:bg-green-700 disabled:bg-green-400 text-white rounded-xl font-semibold transition-all flex items-center justify-center space-x-2"
            >
              {shareLoading ? (
                <>
                  <svg className="animate-spin -ml-1 h-5 w-5" fill="none" viewBox="0 0 24 24">
                    <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
                  </svg>
                  <span>Preparing...</span>
                </>
              ) : (
                <>
                <svg className="w-5 h-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2} strokeLinecap="round" strokeLinejoin="round">
                  <path d="M12 5v14m-5-5l5 5 5-5" />
                </svg>
                  <span>Share on WhatsApp</span>
                </>
              )}
            </button>
            <p className="text-xs text-gray-500 dark:text-gray-400 mt-3">
              📱 Mobile: Auto file attach | 💻 Desktop: Manual attach from Downloads
            </p>
          </div>
        </div>
      </div>

      {/* Preview */}
      <div className="bg-white dark:bg-slate-800 rounded-2xl shadow-lg p-6 border border-gray-100 dark:border-slate-700">
        <div className="flex justify-between items-center mb-4">
          <h3 className="text-lg font-semibold text-gray-900 dark:text-white">📈 Live Preview</h3>
          <button
            onClick={refreshPreview}
            className="px-4 py-2 bg-gray-100 dark:bg-slate-700 text-gray-600 dark:text-gray-300 rounded-lg text-sm font-medium hover:bg-gray-200 dark:hover:bg-slate-600 transition-colors flex items-center space-x-1"
          >
            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" />
            </svg>
            <span>Refresh</span>
          </button>
        </div>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 text-center">
          <div className="bg-blue-50 dark:bg-blue-900/20 rounded-xl p-4">
            <div className="text-2xl font-bold text-blue-600 dark:text-blue-400">{previewStats.tasksCompletedToday}</div>
            <div className="text-xs text-gray-500 dark:text-gray-400">Completed Today</div>
          </div>
          <div className="bg-orange-50 dark:bg-orange-900/20 rounded-xl p-4">
            <div className="text-2xl font-bold text-orange-600 dark:text-orange-400">{previewStats.pendingTasks}</div>
            <div className="text-xs text-gray-500 dark:text-gray-400">Pending</div>
          </div>
          <div className="bg-red-50 dark:bg-red-900/20 rounded-xl p-4">
            <div className="text-2xl font-bold text-red-600 dark:text-red-400">{previewStats.upcomingDeadlines}</div>
            <div className="text-xs text-gray-500 dark:text-gray-400">Deadlines</div>
          </div>
          <div className="bg-green-50 dark:bg-green-900/20 rounded-xl p-4">
            <div className="text-2xl font-bold text-green-600 dark:text-green-400">{previewStats.weeklyProgress}</div>
            <div className="text-xs text-gray-500 dark:text-gray-400">Weekly Progress</div>
          </div>
        </div>
      </div>

      {/* Troubleshooting */}
      <div className="mt-8 p-4 bg-yellow-50 dark:bg-yellow-950/20 rounded-xl border border-yellow-200 dark:border-yellow-800">
        <h4 className="font-semibold text-yellow-900 dark:text-yellow-100 mb-2">💡 Troubleshooting</h4>
        <ul className="text-sm text-yellow-800 dark:text-yellow-200 space-y-1">
          <li>• No download? Check browser Downloads folder + console (F12)</li>
          <li>• Backend not running? Run <code>cd backend && npm run dev</code></li>
          <li>• Auth issue? Login first</li>
          <li>• WhatsApp desktop: Always manual attach from Downloads</li>
        </ul>
      </div>
    </div>
  );
}

export default ReportPage;
