import { motion } from 'framer-motion';
import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { reportService } from '../services/api';
import AnimatedButton from '../components/ui/AnimatedButton';

export default function ReportPage() {
  const navigate = useNavigate();
  const [loading, setLoading] = useState(false);
  const [shareLoading, setShareLoading] = useState(false);
  const [message, setMessage] = useState({ type: '', text: '' });
  const [previewStats, setPreviewStats] = useState({
    tasksCompletedToday: '--', pendingTasks: '--', upcomingDeadlines: '--', weeklyProgress: '--%'
  });

  useEffect(() => { refreshPreview(); }, []);

  const refreshPreview = async () => {
    try {
      const response = await fetch('/api/user/stats', { credentials: 'include', headers: { 'Accept': 'application/json' } });
      if (response.ok) {
        const data = await response.json();
        if (data.success) {
          setPreviewStats({
            tasksCompletedToday: data.data.tasksCompletedToday || 0,
            pendingTasks: data.data.pendingTasks || 0,
            upcomingDeadlines: data.data.upcomingDeadlines || 0,
            weeklyProgress: (data.data.weeklyProgress || 0) + '%',
          });
        }
      }
    } catch (error) { console.warn('Preview stats unavailable:', error); }
  };

  const makeDownload = (blob, filename) => {
    try {
      const url = window.URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = filename;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      window.URL.revokeObjectURL(url);
      return true;
    } catch (error) { console.error('Download failed:', error); throw new Error('Download trigger failed'); }
  };

  const handleDownload = async () => {
    setLoading(true);
    setMessage({ type: '', text: '' });
    try {
      const { blob, filename } = await reportService.getReportBlob();
      if (!blob || blob.size === 0) throw new Error('Empty report generated');
      const success = makeDownload(blob, filename);
      if (success) setMessage({ type: 'success', text: `✅ Report "${filename}" downloaded!` });
    } catch (error) {
      console.error('Download error:', error);
      setMessage({ type: 'error', text: error.message || 'Failed to generate/download report.' });
    } finally { setLoading(false); }
  };

  const handleWhatsAppShare = async () => {
    setShareLoading(true);
    setMessage({ type: '', text: '' });
    try {
      const { blob, filename } = await reportService.getReportBlob();
      if (!blob || blob.size === 0) throw new Error('Empty report generated');
      makeDownload(blob, filename);

      const generatedDate = new Date().toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' });
      const shareText = `📊 *Smart Student Tasks Progress Report*\n\nHi! \n\n✅ I've downloaded my detailed progress report: *${filename}*\n\n*Generated:* ${generatedDate}\n\n📥 **The PDF is now in your Downloads folder. To share:**\n\n1. Open the downloaded PDF from Downloads\n2. In WhatsApp, attach the file from Gallery/Downloads/Documents\n3. Send!\n\n---\n*Generated by Smart Student Tasks app*\n`;

      const isMobile = /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent);
      if (isMobile && navigator.canShare && navigator.canShare({ files: [new File([blob], filename, { type: 'application/pdf' })] })) {
        await navigator.share({ files: [new File([blob], filename, { type: 'application/pdf' })], title: 'Progress Report', text: shareText.split('📥')[0] });
        setMessage({ type: 'success', text: '✅ Report shared natively!' });
      } else {
        window.open(`https://wa.me/?text=${encodeURIComponent(shareText)}`, '_blank', 'noopener,noreferrer');
        setMessage({ type: 'success', text: '✅ PDF downloaded! WhatsApp opened.' });
      }
    } catch (error) {
      console.error('WhatsApp share error:', error);
      setMessage({ type: 'error', text: error.message || 'Share failed.' });
    } finally { setShareLoading(false); }
  };

  return (
    <div className="max-w-4xl mx-auto">
      <div className="mb-6">
        <button onClick={() => navigate('/dashboard')}
          className="text-sm flex items-center gap-1.5 mb-2 hover:opacity-80 transition-opacity"
          style={{ color: 'var(--color-primary)' }}>
          <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" /></svg>
          Back to Dashboard
        </button>
        <h1 className="text-xl sm:text-2xl font-bold tracking-tight" style={{ color: 'var(--text-primary)' }}>Progress Reports</h1>
        <p className="text-sm mt-0.5" style={{ color: 'var(--text-tertiary)' }}>Generate PDF reports and share with others</p>
      </div>

      {message.text && (
        <motion.div initial={{ opacity: 0, y: -8 }} animate={{ opacity: 1, y: 0 }}
          className={`mb-5 p-3.5 rounded-xl flex items-start gap-2.5 text-sm ${
            message.type === 'success' ? 'text-green-400' : 'text-red-400'
          }`}
          style={{ background: message.type === 'success' ? 'rgba(34,197,94,0.1)' : 'rgba(239,68,68,0.1)', border: message.type === 'success' ? '1px solid rgba(34,197,94,0.2)' : '1px solid rgba(239,68,68,0.2)' }}>
          <span>{message.type === 'success' ? '✅' : '❌'}</span>
          <span>{message.text}</span>
        </motion.div>
      )}

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4 sm:gap-6 mb-8">
        {/* Download Card */}
        <motion.div initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 }} className="glass rounded-2xl p-5 sm:p-6 text-center">
          <div className="w-14 sm:w-16 h-14 sm:h-16 mx-auto mb-4 rounded-2xl flex items-center justify-center text-2xl sm:text-3xl" style={{ background: 'rgba(59,130,246,0.1)' }}>
            📥
          </div>
          <h3 className="text-base sm:text-lg font-semibold mb-1" style={{ color: 'var(--text-primary)' }}>Download PDF</h3>
          <p className="text-sm mb-6" style={{ color: 'var(--text-tertiary)' }}>Get a detailed report with charts and stats</p>
          <AnimatedButton onClick={handleDownload} loading={loading} variant="primary" size="lg" className="w-full" icon="📄">
            Download Report
          </AnimatedButton>
        </motion.div>

        {/* WhatsApp Card */}
        <motion.div initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.2 }} className="glass rounded-2xl p-5 sm:p-6 text-center">
          <div className="w-14 sm:w-16 h-14 sm:h-16 mx-auto mb-4 rounded-2xl flex items-center justify-center text-2xl sm:text-3xl" style={{ background: 'rgba(34,197,94,0.1)' }}>
            💬
          </div>
          <h3 className="text-base sm:text-lg font-semibold mb-1" style={{ color: 'var(--text-primary)' }}>Share on WhatsApp</h3>
          <p className="text-sm mb-6" style={{ color: 'var(--text-tertiary)' }}>Downloads PDF first, then opens WhatsApp</p>
          <AnimatedButton onClick={handleWhatsAppShare} loading={shareLoading} variant="success" size="lg" className="w-full" icon="📤">
            Share on WhatsApp
          </AnimatedButton>
          <p className="text-xs mt-2" style={{ color: 'var(--text-tertiary)' }}>
            📱 Mobile: Auto attach · 💻 Desktop: Manual attach
          </p>
        </motion.div>
      </div>

      {/* Live Preview */}
      <motion.div initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.3 }} className="glass rounded-2xl p-4 sm:p-6">
        <div className="flex items-center justify-between mb-4">
          <h3 className="text-base font-semibold" style={{ color: 'var(--text-primary)' }}>📈 Live Preview</h3>
          <button onClick={refreshPreview}
            className="px-3 py-1.5 rounded-lg text-xs font-medium transition-all hover:bg-gray-500/10"
            style={{ color: 'var(--text-secondary)' }}>
            Refresh
          </button>
        </div>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          {[
            { label: 'Completed Today', value: previewStats.tasksCompletedToday, bg: 'rgba(59,130,246,0.08)', text: '#3b82f6' },
            { label: 'Pending', value: previewStats.pendingTasks, bg: 'rgba(234,179,8,0.08)', text: '#eab308' },
            { label: 'Upcoming Deadlines', value: previewStats.upcomingDeadlines, bg: 'rgba(239,68,68,0.08)', text: '#ef4444' },
            { label: 'Weekly Progress', value: previewStats.weeklyProgress, bg: 'rgba(34,197,94,0.08)', text: '#22c55e' },
          ].map((stat, i) => (
            <div key={i} className="rounded-xl p-4 text-center" style={{ background: stat.bg }}>
              <div className="text-2xl font-bold" style={{ color: stat.text }}>{stat.value}</div>
              <div className="text-xs mt-1" style={{ color: 'var(--text-tertiary)' }}>{stat.label}</div>
            </div>
          ))}
        </div>
      </motion.div>

      {/* Troubleshooting */}
      <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 0.4 }}
        className="mt-6 p-3 sm:p-4 rounded-xl" style={{ background: 'rgba(234,179,8,0.08)', border: '1px solid rgba(234,179,8,0.15)' }}>
        <h4 className="text-sm font-semibold mb-2" style={{ color: '#fbbf24' }}>💡 Troubleshooting</h4>
        <ul className="text-xs space-y-1" style={{ color: '#fde68a' }}>
          <li>• No download? Check your browser Downloads folder and console (F12)</li>
          <li>• Backend not running? Run <code>cd backend && npm run dev</code></li>
          <li>• Make sure you're logged in</li>
          <li>• WhatsApp desktop requires manual file attachment from Downloads</li>
        </ul>
      </motion.div>
    </div>
  );
}
